// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htujgbupwjsekwxlqdsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dWpnYnVwd2pzZWt3eGxxZHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDA5MjQsImV4cCI6MjA2ODk3NjkyNH0.UWAQj4p81FdJI8jZo74dS0uunsUvvMyX_CHblQiNnrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});